clusterid: 1234
cloudregionzone: 1234

openshift_cluster_content:
- object: Cluster Autoscaling
  content:
  - name: ClusterAutoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
  - name: MachineAutoscaler zone a
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregionzone }}a"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone b
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregionzone }}b"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone c
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregionzone }}c"
    namespace: openshift-machine-api
