---
clusterid: 1234
cloudregion: 1234
ldap_ca: certificatecontents
ldap_bind_password: password
ldap_bind_dn: uid=admin,cn=users,dc=example,dc=com
ldap_search_url: ldaps://ldap.example.com

openshift_cluster_content:
- object: Cluster Autoscaling
  content:
  - name: ClusterAutoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
  - name: MachineAutoscaler zone a
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}a"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone b
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}b"
    namespace: openshift-machine-api
  - name: MachineAutoscaler zone c
    template: "{{ inventory_dir }}/../templates/machineautoscaler.yaml"
    params_from_vars:
      CLUSTER_ID: "{{ clusterid }}"
      CLOUD_REGION_ZONE: "{{ cloudregion }}c"
    namespace: openshift-machine-api
- object: LDAP Cluster Authentication
  content:
    - name: LDAP Authentication
      template: "{{ inventory_dir }}/../templates/ldap-auth.yaml"
      params_from_vars:
        LDAP_CA: "{{ ldap_ca }}"
        LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
        LDAP_BIND_DN: "{{ ldap_bind_dn }}"
        LDAP_SEARCH_URL: "{{ ldap_search_url }}"
      namespace: openshift-config
      tags:
        - ldap_auth