---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small-size
  namespace: namespace-configuration-operator
spec:
  selector:
    matchLabels:
      size: small
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: small-size
    spec:
      hard:
        requests.cpu: "4"
        requests.memory: "2Gi"
  - apiVersion: v1
    kind: LimitRange
    metadata:
      annotations:
        openshift.io/quota-tier: small
      labels:
        quota-tier: small
      name: limits
    spec:
      limits:
      - defaultRequest:
          cpu: 100m
          memory: 512Mi
        type: Container
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: large-size
  namespace: namespace-configuration-operator
spec:
  selector:
    matchLabels:
      size: large
  resources:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: large-size
    spec:
      hard:
        requests.cpu: "8"
        requests.memory: "4Gi"
  - apiVersion: v1
    kind: LimitRange
    metadata:
      annotations:
        openshift.io/quota-tier: large
      labels:
        quota-tier: large
      name: limits
    spec:
      limits:
      - defaultRequest:
          cpu: 100m
          memory: 512Mi
        type: Container
