# LDAP server URL
ldap_url: "ldap://ipa.example.com"
ldap_ca: "{{ lookup('file', '/path/to/ca.crt') }}"

# LDAP BIND config for authentication and groups sync
ldap_bind_dn: uid=admin,cn=users,cn=accounts,dc=example,dc=com

# Do not store secrets in version control!
ldap_bind_password: "{{ lookup('env', 'LDAP_BIND_PASSWORD') }}"

# LDAP users group
ldap_users_search_base: cn=users,cn=accounts,dc=example,dc=com

# LDAP search URL used during authentication
ldap_auth_search_filter: "(memberOf=cn=ocp-users,cn=groups,cn=accounts,dc=example,dc=com)"
ldap_search_url: "{{ ldap_url }}/{{ ldap_users_search_base }}?uid?sub?{{ ldap_auth_search_filter }}"

# LDAP group sync configuration
ldap_cron_schedule: "@hourly"

# Groups path for LDAP search
ldap_groups_search_base: cn=groups,cn=accounts,dc=example,dc=com

# Optional LDAP groups whitelist
#ldap_groups_whitelist: |
#  cn=ocp-admins,cn=groups,cn=accounts,dc=example,dc=com
#  cn=ocp-users,cn=groups,cn=accounts,dc=example,dc=com
