---
# Exclude cluster-secrets when run from Eunomia GitOps operator
exclude_tags: cluster-secrets

openshift_cluster_content:
- galaxy_requirements: "{{ inventory_dir }}/../requirements.yml"
- object: Setup and Discovery
  pre_steps:
  - role: self/roles/discover
  content:
  - name: GitOps Config
    template: "{{ inventory_dir }}/../templates/cluster-gitops.yaml"
    params_from_vars:
      CLUSTER_CONFIG_REPO_REF: master
      TEMPLATE_PROCESSOR_IMAGE: quay.io/etsauer/eunomia-applier:latest
    tags:
    - gitops
- object: OpenShift Machine API
  content:
  - name: Custom Machinesets
    file: "{{ inventory_dir }}/../manifests/custom-machinesets.j2"
    tags:
    - openshift-machine-api
  - name: Default Machinesets
    file: "{{ inventory_dir }}/../manifests/default-machinesets.j2"
    tags:
    - openshift-machine-api
    post_steps:
    - role: self/roles/openshift_machine_api
  - name: Cluster Autoscaler
    file: "{{ inventory_dir }}/../manifests/clusterautoscaler.yaml"
- object: Scheduler
  content:
  - name: Cluster Autoscaler
    file: "{{ inventory_dir }}/../manifests/scheduler.j2"
- object: LDAP Cluster Secrets
  content:
  - name: LDAP Secrets
    template: "{{ inventory_dir }}/../templates/ldap-cluster-secrets.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
    namespace: openshift-config
    tags:
    - cluster-secrets
  - name: LDAP Authentication
    template: "{{ inventory_dir }}/../templates/ldap-auth.yaml"
    params_from_vars:
      LDAP_CA: "{{ ldap_ca }}"
      LDAP_BIND_PASSWORD: "{{ ldap_bind_password }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_SEARCH_URL: "{{ ldap_search_url }}"
    namespace: openshift-config
    tags:
    - ldap_auth
- object: LDAP Group Synchronization
  content:
  - name: LDAP Group Synchronization
    template: "{{ inventory_dir }}/../templates/ldap-group-sync.yaml"
    params_from_vars:
      LDAP_GROUPS_SEARCH_BASE: "{{ ldap_groups_search_base }}"
      LDAP_BIND_DN: "{{ ldap_bind_dn }}"
      LDAP_URL: "{{ ldap_url }}"
      LDAP_USERS_SEARCH_BASE: "{{ ldap_users_search_base }}"
      LDAP_GROUPS_WHITELIST: "{{ ldap_groups_whitelist | default('') }}"
      SCHEDULE: "{{ ldap_cron_schedule }}"
    namespace: openshift-config
    tags:
    - ldap_group_sync
- object: Setup AWS StorageClasses
  content:
  - name: Setup AWS StorageClasses
    template: "{{ inventory_dir }}/../templates/aws-ebs-storage-classes.yaml"
    params_from_vars:
      ENCRYPT_STORAGE: "{{ aws_sc_encrypt_storage }}"
    namespace: openshift-config
    tags:
    - aws
    - aws-storage-classes

# Variables set dynamically by set_fact in discover role
infraid: ''
cloudregion: ''
